[package]
authors = ["Rouven Reuter"]
description = "A template for rust projects build by the robinson group"
edition = "2024"
homepage = "https://robinsongroup.github.io/"
license = "MIT"
name = "robinson-group-rust-template"
version = "0.1.0"

[dependencies]
thiserror = "2.0.18"
maplit = "1.0.2"
chrono = "0.4.41"
strum = { version = "0.28", features = ["derive"] }
uuid = { version = "1.23.1", features = ["v4"] }
csv = "1.3"

[dev-dependencies]
ontology-registry = "0.4.2"
ontolius = "0.7.4"