[package]
authors = ["Rouven Reuter <Rouven.Reuter@proton.me>"]
description = "A template for rust projects build by the robinson group"
edition = "2024"
homepage = "https://robinsongroup.github.io/"
license = "MIT"
name = "robinson-group-rust-template"
version = "0.1.0"

[dependencies]
thiserror = "2.0.18"
maplit = "1.0.2"
chrono = "0.4.41"


[dev-dependencies]
polars = "0.53.0"
image = "0.25.9"
phenopackets = { version = "0.2.2-post2", features = ["serde"] }
serde = "1.0.228"
serde_json = { version = "1.0.149", features = ["preserve_order"] }
prost-types = "0.14"

